### ISSUE TITLE
mysql-router charm shows WEB support 20.04, but 20.04 + 22.04 uploaded to charmstore

### ISSUE THREAD

**Issue by taurus-forever** [canonical/charmhub.io#1658]
Hi,

Based on https://chat.charmhub.io/charmhub/pl/awz34ux3utgz5yowpn6mgysdgw

TL;DR: see the picture:
![Screenshot from 2023-08-25 15-45-10](https://github.com/canonical/charmhub.io/assets/1928266/017bdfc6-3111-455f-9ab0-5925051478fd)

As you can see 22.04 badge is missing for mysql-router in `dpe/edge`, but it the charm available for both focal and jammy:
```
> juju download mysql-router --channel dpe/edge --series jammy
Fetching charm "mysql-router" revision 100 using "dpe/edge" channel and base "amd64/ubuntu/22.04"
Install the "mysql-router" charm with:
    juju deploy ./mysql-router_r100.charm

> juju download mysql-router --channel dpe/edge --series focal
Fetching charm "mysql-router" revision 101 using "dpe/edge" channel and base "amd64/ubuntu/20.04"
Install the "mysql-router" charm with:
    juju deploy ./mysql-router_r101.charm
```

Can you please share the reason for the current charmhub.io behavior? Tnx!

**Comment by taurus-forever** [comment]
Just for the history: charmcraft built and published two revisions for series `jammy=100` and `focal=101` for [such configuration](https://github.com/canonical/mysql-router-operator/blob/main/charmcraft.yaml#L9-L20).

However, in fact it is the same charm for different series. CharmHub.io shows the last revision only => revision for Jammy is not shown.

CharmHub or Charmcraft should be improved. CC: @sergiusens

**Comment by sergiusens** [comment]
From all the information shared, this so far looks like a Charmhub issue. 

```
sergiusens@imladris:~/mysql$ cat 102/manifest.yaml | yq .bases
- architectures:
    - amd64
  channel: '22.04'
  name: ubuntu
sergiusens@imladris:~/mysql$ cat 103/manifest.yaml | yq .bases
- architectures:
    - amd64
  channel: '20.04'
  name: ubuntu
```

@taurus-forever can you provide the output for `charmcraft status mysql-router`? This sould take the base as an axis.
