### ISSUE TITLE
Resource description is rendered incorrectly

### ISSUE THREAD

**Issue by sed-i** [canonical/charmhub.io#1706]
In [metadata](https://github.com/canonical/traefik-k8s-operator/blob/main/metadata.yaml), I have:

```yaml
resources:
  traefik-image:
    type: oci-image
    description: |
      OCI image for traefik. This charms makes the following assumptions about the image:
      - executable is `/usr/bin/traefik`
      - has `update-ca-certificates`
    upstream-source: docker.io/ubuntu/traefik:2-22.04
```

but on charmhub it is rendered as plain text, and is missing the `upstream-source` property:
![image](https://github.com/canonical/charmhub.io/assets/82407168/9b607cd9-7138-49a5-8fd5-f5be37862ee1)
